# Generated by Django 6.0.2 on 2026-03-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_remove_customer_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='logo',
        ),
        migrations.AddField(
            model_name='business',
            name='enable_tax',
            field=models.BooleanField(default=True, help_text='Enable tax calculations'),
        ),
        migrations.AddField(
            model_name='business',
            name='tax_name',
            field=models.CharField(default='VAT', help_text='Name of the tax (e.g., VAT, GST, Sales Tax)', max_length=50),
        ),
        migrations.AddField(
            model_name='business',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=16.0, help_text='Tax rate in percentage', max_digits=5),
        ),
        migrations.AlterField(
            model_name='business',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='subdomain',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
