# Generated by Django 6.0.2 on 2026-03-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_remove_business_logo_business_enable_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='daraja_callback_url',
            field=models.URLField(blank=True, help_text='Callback URL for M-Pesa transactions'),
        ),
        migrations.AddField(
            model_name='business',
            name='daraja_consumer_key',
            field=models.CharField(blank=True, help_text='Daraja Consumer Key', max_length=255),
        ),
        migrations.AddField(
            model_name='business',
            name='daraja_consumer_secret',
            field=models.CharField(blank=True, help_text='Daraja Consumer Secret', max_length=255),
        ),
        migrations.AddField(
            model_name='business',
            name='daraja_initiator_name',
            field=models.CharField(blank=True, help_text='Initiator Name for transactions', max_length=100),
        ),
        migrations.AddField(
            model_name='business',
            name='daraja_passkey',
            field=models.CharField(blank=True, help_text='Daraja Pass Key', max_length=255),
        ),
        migrations.AddField(
            model_name='business',
            name='daraja_shortcode',
            field=models.CharField(blank=True, help_text='Business Short Code', max_length=10),
        ),
        migrations.AddField(
            model_name='business',
            name='enable_daraja',
            field=models.BooleanField(default=False, help_text='Enable Daraja API for M-Pesa payments'),
        ),
    ]
