# Generated by Django 6.0.3 on 2026-03-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_business_daraja_callback_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customer_phone',
            field=models.CharField(blank=True, help_text='Customer phone number for M-Pesa payments', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='mpesa_transaction_id',
            field=models.CharField(blank=True, help_text='M-Pesa transaction ID', max_length=50),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('M-Pesa', 'M-Pesa'), ('Bank Transfer', 'Bank Transfer')], max_length=20),
        ),
    ]
