# Generated by Django 6.0.3 on 2026-03-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_sale_customer_phone_sale_mpesa_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['business'], name='pos_product_busines_ff0bde_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['business', 'name'], name='pos_product_busines_95ae1d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['business', 'barcode'], name='pos_product_busines_e3943c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['business', 'category'], name='pos_product_busines_8c5a2c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['business', 'is_active'], name='pos_product_busines_7de660_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['business'], name='pos_sale_busines_483aa1_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['business', 'sale_number'], name='pos_sale_busines_c51fcf_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['business', 'cashier'], name='pos_sale_busines_cc6470_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['business', 'sale_date'], name='pos_sale_busines_a68915_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['business', 'payment_method'], name='pos_sale_busines_b08f21_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['business', 'payment_status'], name='pos_sale_busines_668a11_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['mpesa_transaction_id'], name='pos_sale_mpesa_t_472cce_idx'),
        ),
    ]
