# Generated by Django 6.0.3 on 2026-03-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pos', '0006_product_pos_product_busines_ff0bde_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='business',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='business',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='subscription_plan',
            field=models.CharField(db_index=True, default='Basic', max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='is_completed',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='mpesa_transaction_id',
            field=models.CharField(blank=True, db_index=True, help_text='M-Pesa transaction ID', max_length=50),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('M-Pesa', 'M-Pesa'), ('Bank Transfer', 'Bank Transfer')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Partial', 'Partial'), ('Cancelled', 'Cancelled')], db_index=True, default='Paid', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_number',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_business_admin',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(db_index=True, default='Cashier', max_length=20),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['name'], name='pos_busines_name_3be700_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['is_active'], name='pos_busines_is_acti_398ff1_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['created_at'], name='pos_busines_created_82b84f_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['subscription_plan'], name='pos_busines_subscri_917553_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['is_active', 'subscription_plan'], name='pos_busines_is_acti_bb3d99_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['business', 'name'], name='pos_categor_busines_96a02d_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['business', 'is_active'], name='pos_categor_busines_5d4432_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['business', 'created_at'], name='pos_categor_busines_56efa0_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='pos_categor_name_318abe_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active'], name='pos_categor_is_acti_80a30d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['business', 'stock_quantity'], name='pos_product_busines_2d3143_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['business', 'created_at'], name='pos_product_busines_008a28_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['barcode'], name='pos_product_barcode_d45943_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='pos_product_name_93ae43_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['stock_quantity'], name='pos_product_stock_q_73fd3f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'stock_quantity'], name='pos_product_is_acti_190e10_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['business', 'is_active', 'stock_quantity'], name='pos_product_busines_f5a2a9_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['business', 'total_amount'], name='pos_sale_busines_fda874_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sale_date'], name='pos_sale_sale_da_1741af_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['payment_method'], name='pos_sale_payment_391f85_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['payment_status'], name='pos_sale_payment_e5b274_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['business', 'sale_date', 'payment_status'], name='pos_sale_busines_e800c8_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['business', 'payment_method', 'sale_date'], name='pos_sale_busines_254425_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['business'], name='pos_user_busines_0a62dd_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['business', 'role'], name='pos_user_busines_245d76_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['business', 'is_business_admin'], name='pos_user_busines_9dc0d7_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='pos_user_role_c357b7_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_business_admin'], name='pos_user_is_busi_a09d5a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='pos_user_created_301f22_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='pos_user_usernam_4c3854_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='pos_user_email_01250c_idx'),
        ),
    ]
